// main.js — boot orchestrator + compose-modal controller. Architect-owned.
// Contracts in ARCHITECTURE.md. Builders: do not edit this file.

import { app, bus } from './state.js';
import {
  initDB, listEntries, getEntry, saveEntry, softDeleteEntry,
  putBlob, getBlob, deleteBlob
} from './store.js';
import { uid, toast, confirmDialog, blobUrl, releaseBlobUrl, revokeAll } from './util.js';
import { initBook } from './book.js';
import { initJournal } from './journal.js';
import { initSync } from './sync.js';
import { initExporter } from './exporter.js';
import { initShareCard } from './sharecard.js';
import { initDrive } from './drive.js';
import { ingestFiles } from './ingest.js';
import { reverseGeocode, forwardGeocode } from './geocode.js';
import { initDictation, createVoiceRecorder } from './voice.js';

const $ = (id) => document.getElementById(id);

const THEMES = ['passport', 'minimal', 'scrapbook'];
const THEME_KEY = 'wayfarer-theme';

/* =========================================================================
   THEME
   ========================================================================= */

function applyTheme(theme) {
  if (!THEMES.includes(theme)) theme = 'passport';
  app.settings.theme = theme;
  document.documentElement.setAttribute('data-app-theme', theme);
  try { localStorage.setItem(THEME_KEY, theme); } catch (e) { /* private mode */ }
  for (const btn of document.querySelectorAll('#theme-picker [data-app-theme]')) {
    btn.setAttribute('aria-pressed', String(btn.dataset.appTheme === theme));
  }
}

function initTheme() {
  let saved = null;
  try { saved = localStorage.getItem(THEME_KEY); } catch (e) { /* private mode */ }
  applyTheme(saved || app.settings.theme);
  $('theme-picker').addEventListener('click', (e) => {
    const btn = e.target.closest('[data-app-theme]');
    if (btn) applyTheme(btn.dataset.appTheme);
  });
}

/* =========================================================================
   VIEWS
   ========================================================================= */

function applyView(view) {
  if (view !== 'book' && view !== 'journal') view = 'book';
  app.view = view;
  $('book-root').hidden = view !== 'book';
  $('journal-root').hidden = view !== 'journal';
  for (const btn of document.querySelectorAll('#view-toggle [data-view]')) {
    btn.setAttribute('aria-pressed', String(btn.dataset.view === view));
  }
  bus.emit('view-changed', { view });
}

function initViewToggle() {
  $('view-toggle').addEventListener('click', (e) => {
    const btn = e.target.closest('[data-view]');
    if (btn && btn.dataset.view !== app.view) applyView(btn.dataset.view);
  });
}

/* =========================================================================
   ENTRIES CACHE
   ========================================================================= */

async function refreshEntriesCache() {
  try {
    app.entries = await listEntries();
  } catch (err) {
    console.error('Wayfarer: failed to load entries', err);
    toast('Couldn’t read your diary from storage.', 'error');
    app.entries = [];
  }
}

/* =========================================================================
   COMPOSE CONTROLLER
   ========================================================================= */

const compose = {
  open: false,
  editingId: null,          // entry id when editing, else null
  editingEntry: null,       // original entry object when editing
  photos: [],               // [{ blobRec, persisted: bool }] in display order
  removedPersistedIds: [],  // saved blob ids the user removed while editing
  geo: null,                // { lat, lon } from EXIF, if any
  locationFromExif: false,  // location input value came from a photo
  dateAuto: false,          // date field still holds our default (today) — EXIF may replace it
  recorder: null,           // voice recorder handle for this session
  existingVoiceId: null,    // voiceId already saved on the entry being edited
  busy: false
};

let dictation = null;       // handle from initDictation — stopped on compose close
let photoOnlyHintEl = null; // quiet 'photos can stand alone' line under the story field

function todayISO() {
  const d = new Date();
  const p = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
}

function setLocationStatus(text) {
  $('compose-location-status').textContent = text;
}

/**
 * Photo-only reassurance: when photos exist and the story is empty, a quiet
 * hint under the story field says no words are required. Purely informative —
 * never a nag, never a validation state (photo-only entries save fine).
 */
function updatePhotoOnlyHint() {
  if (!photoOnlyHintEl) return;
  const storyEmpty = $('compose-story').value.trim() === '';
  photoOnlyHintEl.hidden = !(compose.photos.length > 0 && storyEmpty);
}

function renderPhotoList() {
  const list = $('compose-photo-list');
  list.textContent = '';
  compose.photos.forEach(({ blobRec }, index) => {
    const li = document.createElement('li');
    const img = document.createElement('img');
    img.src = blobUrl(blobRec.id, blobRec.blob);
    img.alt = `Photo ${index + 1} of ${compose.photos.length}`;
    const rm = document.createElement('button');
    rm.type = 'button';
    rm.className = 'photo-remove';
    rm.textContent = '×';
    rm.setAttribute('aria-label', `Remove photo ${index + 1}`);
    rm.addEventListener('click', () => removePhoto(blobRec.id));
    li.append(img, rm);
    list.appendChild(li);
  });
  // Photo add/remove and compose open all funnel through here — one choke
  // point keeps the photo-only hint honest without extra wiring.
  updatePhotoOnlyHint();
}

function removePhoto(blobId) {
  const idx = compose.photos.findIndex((p) => p.blobRec.id === blobId);
  if (idx === -1) return;
  const [removed] = compose.photos.splice(idx, 1);
  if (removed.persisted) {
    // Blob (and its shared object URL) may still be shown by the book/journal
    // behind the modal — defer deletion + URL revocation to save time.
    compose.removedPersistedIds.push(blobId);
  } else {
    releaseBlobUrl(blobId);
  }
  renderPhotoList();
}

async function addFiles(files) {
  if (!files || !files.length) return;
  const drop = $('compose-photos-drop');
  drop.setAttribute('aria-busy', 'true');
  setLocationStatus('Reading photos…');
  let results = [];
  try {
    results = await ingestFiles(files);
  } catch (err) {
    console.warn('Wayfarer: ingest failed', err);
  }
  drop.removeAttribute('aria-busy');
  if (!results.length) {
    // Stub ingest or no readable images — quiet, useful guidance; never an error tone.
    setLocationStatus(compose.geo ? 'Location from photo' : 'Add location');
    if (files.length) toast('No photos could be added from that selection.', 'info');
    return;
  }
  for (const r of results) {
    compose.photos.push({ blobRec: r.blobRec, persisted: false });
  }
  renderPhotoList();
  await prefillFromExif(results);
}

/** Prefill date + location from the first photo carrying GPS/date EXIF. */
async function prefillFromExif(results) {
  // The date input is never empty (openCompose defaults it to today), so the
  // guard is "the value is still our automatic default", not "empty". dateISO
  // is the date of the MEMORY — last month's vacation photos must not produce
  // an entry silently dated today.
  const withDate = results.find((r) => r.exif && r.exif.takenAt);
  if (withDate && (compose.dateAuto || !$('compose-date').value)) {
    const iso = String(withDate.exif.takenAt).slice(0, 10);
    if (/^\d{4}-\d{2}-\d{2}$/.test(iso)) {
      $('compose-date').value = iso;
      compose.dateAuto = false; // first photo's capture date wins; later batches don't churn it
    }
  }

  const withGps = results.find((r) => r.exif && r.exif.lat != null && r.exif.lon != null);
  if (!withGps) {
    if (!compose.geo && !$('compose-location').value.trim()) setLocationStatus('Add location');
    return;
  }
  if (compose.geo || $('compose-location').value.trim()) return; // don't clobber

  compose.geo = { lat: withGps.exif.lat, lon: withGps.exif.lon };
  setLocationStatus('Finding where this was taken…');
  let name = null;
  try {
    name = await reverseGeocode(withGps.exif.lat, withGps.exif.lon);
  } catch (err) { /* geocode never throws per contract, but stay safe */ }
  if (!compose.open) return; // modal closed while we were looking it up
  if (name && !$('compose-location').value.trim()) {
    $('compose-location').value = name;
    compose.locationFromExif = true;
    setLocationStatus('Location from photo');
  } else {
    // Offline / stub / no result: we still keep the coordinates — never show an error.
    compose.locationFromExif = $('compose-location').value.trim() === '';
    setLocationStatus(compose.locationFromExif ? 'Location from photo' : 'Add location');
  }
}

async function openCompose(entryId = null) {
  const dlg = $('compose-modal');
  if (compose.open || typeof dlg.showModal !== 'function') {
    if (typeof dlg.showModal !== 'function') {
      toast('This browser can’t open the entry editor (no dialog support). Please use a current browser.', 'error');
    }
    return;
  }

  // reset state
  compose.open = true;
  compose.editingId = entryId;
  compose.editingEntry = null;
  compose.photos = [];
  compose.removedPersistedIds = [];
  compose.geo = null;
  compose.locationFromExif = false;
  compose.dateAuto = !entryId; // new entry: today is only a default, EXIF may improve it
  compose.existingVoiceId = null;
  compose.busy = false;

  $('compose-title').value = '';
  $('compose-date').value = todayISO();
  $('compose-location').value = '';
  $('compose-story').value = '';
  setLocationStatus('Add location');
  $('compose-heading').textContent = entryId ? 'Edit entry' : 'New entry';
  $('compose-delete').hidden = !entryId;
  $('compose-save').disabled = false;

  let existingVoiceBlob = null; // saved voice note, shown playable in the recorder

  if (entryId) {
    const entry = await getEntry(entryId);
    if (!entry || entry.deleted) {
      compose.open = false;
      toast('That entry can’t be found any more.', 'error');
      return;
    }
    compose.editingEntry = entry;
    $('compose-title').value = entry.title || '';
    if (entry.dateISO) $('compose-date').value = entry.dateISO;
    $('compose-location').value = entry.location?.name || '';
    if (entry.location && entry.location.lat != null) {
      compose.geo = { lat: entry.location.lat, lon: entry.location.lon };
    }
    compose.locationFromExif = entry.location?.source === 'exif';
    setLocationStatus(entry.location?.name
      ? (compose.locationFromExif ? 'Location from photo' : ' ')
      : 'Add location');
    $('compose-story').value = entry.story || '';
    compose.existingVoiceId = entry.voiceId || null;
    if (compose.existingVoiceId) {
      try {
        const vrec = await getBlob(compose.existingVoiceId);
        if (vrec && vrec.blob) existingVoiceBlob = vrec.blob;
      } catch (err) { /* blob missing — recorder falls back to idle */ }
    }
    for (const pid of entry.photoIds || []) {
      const rec = await getBlob(pid);
      if (rec) compose.photos.push({ blobRec: rec, persisted: true });
    }
    renderPhotoList();
  } else {
    renderPhotoList();
  }

  // fresh voice recorder each session; an existing saved note renders as a
  // playable "Saved voice note" with Re-record / Remove
  const voiceRoot = $('compose-voice-root');
  voiceRoot.textContent = '';
  try {
    compose.recorder = createVoiceRecorder(voiceRoot, existingVoiceBlob);
  } catch (err) {
    console.warn('Wayfarer: voice recorder unavailable', err);
    compose.recorder = null;
  }

  dlg.showModal();
  $('compose-title').focus();
}

function closeCompose(saved, entryId) {
  const dlg = $('compose-modal');
  // release preview URLs for photos that were never persisted
  for (const p of compose.photos) {
    if (!p.persisted) releaseBlobUrl(p.blobRec.id);
  }
  if (compose.recorder) {
    try { compose.recorder.reset(); } catch (e) { /* noop */ }
    compose.recorder = null;
  }
  // never leave dictation (and the mic indicator) running behind a closed dialog
  if (dictation) {
    try { dictation.stop(); } catch (e) { /* noop */ }
  }
  compose.open = false;
  compose.photos = [];
  compose.editingEntry = null;
  if (dlg.open) dlg.close();
  bus.emit('compose-close', { saved: !!saved, entryId });
}

/** Anything typed, added, or recorded that a close would throw away? */
function composeHasUnsavedWork() {
  const title = $('compose-title').value.trim();
  const story = $('compose-story').value.trim();
  const locName = $('compose-location').value.trim();
  const newRec = compose.recorder ? compose.recorder.getResult() : null;
  const removedExisting = !!(compose.existingVoiceId && compose.recorder
    && typeof compose.recorder.existingRemoved === 'function'
    && compose.recorder.existingRemoved());

  if (!compose.editingId) {
    return !!(title || story || locName || compose.photos.length || (newRec && newRec.blob));
  }
  const base = compose.editingEntry || {};
  const basePhotos = (base.photoIds || []).join('\n');
  const curPhotos = compose.photos.map((p) => p.blobRec.id).join('\n');
  return title !== (base.title || '')
    || $('compose-date').value !== (base.dateISO || $('compose-date').value)
    || locName !== ((base.location && base.location.name) || '')
    || story !== (base.story || '')
    || curPhotos !== basePhotos
    || !!(newRec && newRec.blob)
    || removedExisting;
}

/** Cancel / Esc / dialog-close path: confirm before discarding real work. */
async function requestCloseCompose() {
  if (!compose.open || compose.busy) return;
  if (composeHasUnsavedWork()) {
    const ok = await confirmDialog(
      'Discard this entry? Unsaved photos, story and voice note will be lost.',
      true, 'Discard'
    );
    if (!ok || !compose.open) return; // keep writing (or already closed meanwhile)
  }
  closeCompose(false, compose.editingId);
}

async function saveCompose() {
  if (compose.busy) return;
  const story = $('compose-story').value.trim();
  if (compose.photos.length === 0 && !story) {
    toast('Add at least one photo, or write (or dictate) a few words first.', 'warning');
    $('compose-story').focus();
    return;
  }

  compose.busy = true;
  $('compose-save').disabled = true;

  try {
    const locationText = $('compose-location').value.trim();

    // Resolve the location object
    let location = { name: '', lat: null, lon: null, source: 'none' };
    if (locationText) {
      if (compose.locationFromExif && compose.geo) {
        location = { name: locationText, lat: compose.geo.lat, lon: compose.geo.lon, source: 'exif' };
      } else {
        let lat = compose.geo ? compose.geo.lat : null;
        let lon = compose.geo ? compose.geo.lon : null;
        // Manually typed/edited location: try to pin it (fine if this returns null offline).
        try {
          const hit = await forwardGeocode(locationText);
          if (hit) { lat = hit.lat; lon = hit.lon; }
        } catch (e) { /* contract says never throws; stay safe */ }
        location = { name: locationText, lat, lon, source: 'manual' };
      }
    } else if (compose.geo) {
      // GPS known but no readable name (offline): keep the pin, unnamed.
      location = { name: '', lat: compose.geo.lat, lon: compose.geo.lon, source: 'exif' };
    }

    // Persist new photo blobs
    for (const p of compose.photos) {
      if (!p.persisted) {
        await putBlob(p.blobRec);
        p.persisted = true;
      }
    }

    // Voice note: a new recording replaces any existing one; an explicit
    // "Remove" in the recorder deletes the saved note (the widget shows the
    // existing note playable with Re-record / Remove while editing).
    let voiceId = compose.existingVoiceId;
    const rec = compose.recorder ? compose.recorder.getResult() : null;
    const removedExisting = !!(compose.recorder
      && typeof compose.recorder.existingRemoved === 'function'
      && compose.recorder.existingRemoved());
    if (rec && rec.blob) {
      const audioRec = {
        id: uid(), blob: rec.blob, kind: 'audio',
        w: 0, h: 0, mime: rec.mime || rec.blob.type || 'audio/webm'
      };
      await putBlob(audioRec);
      if (compose.existingVoiceId) {
        await deleteBlob(compose.existingVoiceId);
        releaseBlobUrl(compose.existingVoiceId);
      }
      voiceId = audioRec.id;
    } else if (removedExisting && compose.existingVoiceId) {
      await deleteBlob(compose.existingVoiceId);
      releaseBlobUrl(compose.existingVoiceId);
      voiceId = null;
    }

    // Delete photo blobs the user removed from a saved entry
    for (const id of compose.removedPersistedIds) {
      await deleteBlob(id);
      releaseBlobUrl(id); // blob is gone — drop its cached object URL too
    }
    compose.removedPersistedIds = [];

    const base = compose.editingEntry || {};
    const entry = {
      id: compose.editingId || uid(),
      title: $('compose-title').value.trim(),
      dateISO: $('compose-date').value || todayISO(),
      location,
      story,
      photoIds: compose.photos.map((p) => p.blobRec.id),
      voiceId: voiceId || null,
      createdAt: base.createdAt || '',
      updatedAt: '',
      deleted: false
    };
    await saveEntry(entry);

    await refreshEntriesCache();
    bus.emit('entries-changed', { reason: 'save' });
    toast(compose.editingId ? 'Entry updated.' : 'Entry added to your diary.', 'success');
    closeCompose(true, entry.id);
  } catch (err) {
    console.error('Wayfarer: save failed', err);
    toast('Couldn’t save the entry. Please try again.', 'error');
  } finally {
    compose.busy = false;
    $('compose-save').disabled = false;
  }
}

async function deleteComposeEntry() {
  if (!compose.editingId || compose.busy) return;
  const ok = await confirmDialog(
    'Delete this entry? It will disappear from your diary (its photos stay in exports you already made).',
    true
  );
  if (!ok) return;
  compose.busy = true;
  try {
    await softDeleteEntry(compose.editingId);
    await refreshEntriesCache();
    bus.emit('entries-changed', { reason: 'delete' });
    toast('Entry deleted.', 'success');
    closeCompose(false, compose.editingId);
  } catch (err) {
    console.error('Wayfarer: delete failed', err);
    toast('Couldn’t delete the entry.', 'error');
  } finally {
    compose.busy = false;
  }
}

function initCompose() {
  const dlg = $('compose-modal');
  const drop = $('compose-photos-drop');
  const input = $('compose-photo-input');

  // open triggers
  $('btn-new-entry').addEventListener('click', () => openCompose(null));
  bus.on('compose-open', (d) => openCompose(d && d.entryId ? d.entryId : null));

  // photo pick + drop
  drop.addEventListener('click', () => input.click());
  drop.addEventListener('keydown', (e) => {
    if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); input.click(); }
  });
  input.addEventListener('change', async (e) => {
    await addFiles(e.target.files);
    input.value = '';
  });
  for (const evt of ['dragenter', 'dragover']) {
    drop.addEventListener(evt, (e) => { e.preventDefault(); drop.classList.add('drag-over'); });
  }
  for (const evt of ['dragleave', 'drop']) {
    drop.addEventListener(evt, (e) => { e.preventDefault(); drop.classList.remove('drag-over'); });
  }
  drop.addEventListener('drop', (e) => {
    if (e.dataTransfer && e.dataTransfer.files && e.dataTransfer.files.length) {
      addFiles(e.dataTransfer.files);
    }
  });

  // typing a location by hand makes it manual
  $('compose-location').addEventListener('input', () => {
    compose.locationFromExif = false;
    setLocationStatus($('compose-location').value.trim() ? ' ' : 'Add location');
  });

  // a hand-picked date is never overwritten by EXIF prefill
  $('compose-date').addEventListener('input', () => { compose.dateAuto = false; });

  // photo-only reassurance line, styled like the other quiet field hints.
  // Built here (index.html is frozen) and slotted under the story field's
  // status area; dictation dispatches 'input' too, so it stays in sync.
  photoOnlyHintEl = document.createElement('p');
  photoOnlyHintEl.className = 'field-status';
  photoOnlyHintEl.textContent = 'No words needed — photos can stand alone.';
  photoOnlyHintEl.hidden = true;
  $('compose-dictation-status').insertAdjacentElement('afterend', photoOnlyHintEl);
  $('compose-story').addEventListener('input', updatePhotoOnlyHint);

  // dictation (voice.js handles unsupported/permission states in the status line)
  try {
    dictation = initDictation({
      textarea: $('compose-story'),
      button: $('compose-mic-btn'),
      statusEl: $('compose-dictation-status')
    }) || null;
  } catch (err) {
    console.warn('Wayfarer: dictation init failed', err);
    $('compose-mic-btn').disabled = true;
  }

  // actions
  $('compose-save').addEventListener('click', saveCompose);
  $('compose-cancel').addEventListener('click', () => { requestCloseCompose(); });
  $('compose-delete').addEventListener('click', deleteComposeEntry);

  // Esc / dialog-native close — both funnel through the discard confirmation
  dlg.addEventListener('cancel', (e) => { e.preventDefault(); requestCloseCompose(); });
  dlg.addEventListener('close', () => { if (compose.open) closeCompose(false, compose.editingId); });
}

/* =========================================================================
   HEADER OVERFLOW MENU (the '⋯' <details>)
   =========================================================================
   Native <details> never closes itself — without this, choosing "Save diary"
   leaves the popover open on top of the view toggle. Close it after any
   menu action, on Esc, and on click-outside, like every menu users know. */

function initHeaderMenu() {
  const more = document.querySelector('.header-more');
  if (!more) return;
  const summary = more.querySelector('summary');

  // choosing any action closes the menu
  more.addEventListener('click', (e) => {
    if (e.target.closest('.header-more-menu button')) more.open = false;
  });

  // click / tap outside closes it
  document.addEventListener('pointerdown', (e) => {
    if (more.open && !more.contains(e.target)) more.open = false;
  });

  // Esc closes it and returns focus to the trigger
  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && more.open) {
      more.open = false;
      if (summary) summary.focus();
    }
  });
}

/* =========================================================================
   BOOT
   ========================================================================= */

async function boot() {
  initTheme();

  await initDB();
  await refreshEntriesCache();

  // auth first (dynamic import per architecture) — decides local vs cloud mode
  try {
    const auth = await import('./auth.js');
    await auth.initAuth();
  } catch (err) {
    console.error('Wayfarer: auth init failed — keeping the sign-in gate up', err);
    const gate = $('login-gate');
    if (gate) {
      gate.hidden = false; // sign-in required: never reveal the app on auth failure
      const st = $('login-status');
      if (st) st.textContent = 'Sign-in is temporarily unavailable. Please reload the page.';
    }
  }

  // views
  try { initBook($('book-root')); } catch (err) { console.error('Wayfarer: book init failed', err); }
  try { initJournal($('journal-root')); } catch (err) { console.error('Wayfarer: journal init failed', err); }

  // services
  try { initSync(); } catch (err) { console.error('Wayfarer: sync init failed', err); }
  try { initExporter(); } catch (err) { console.error('Wayfarer: exporter init failed', err); }
  try { initShareCard(); } catch (err) { console.error('Wayfarer: share init failed', err); }
  // Google Drive import — self-gates on config.GOOGLE_* (stays dormant/offline when unset).
  try { initDrive('.header-more-menu'); } catch (err) { console.error('Wayfarer: drive init failed', err); }

  // shell wiring
  initViewToggle();
  initCompose();
  initHeaderMenu();

  $('btn-load-demo').addEventListener('click', async () => {
    const btn = $('btn-load-demo');
    btn.disabled = true;
    try {
      const demo = await import('./demo.js');
      await demo.loadDemo();
    } catch (err) {
      console.error('Wayfarer: demo failed', err);
      toast('Couldn’t load the demo trip.', 'error');
    } finally {
      btn.disabled = false;
    }
  });

  $('btn-signout').addEventListener('click', async () => {
    try {
      const auth = await import('./auth.js');
      await auth.signOut();
    } catch (err) {
      console.error('Wayfarer: sign out failed', err);
      toast('Sign out failed.', 'error');
    }
  });

  // bus plumbing
  bus.on('toast', (d) => { if (d && d.message) toast(d.message, d.kind || 'info'); });
  // Emitters like demo/import/sync don't update app.entries themselves; views
  // render synchronously from it, so refresh the cache and re-announce once.
  bus.on('entries-changed', async (d) => {
    if (d && d.reason === 'cache-refreshed') return;
    await refreshEntriesCache();
    bus.emit('entries-changed', { reason: 'cache-refreshed' });
  });

  // reveal the app
  const splash = $('boot-splash');
  if (splash) splash.remove();
  $('app').hidden = false;
  applyView(app.view);

  // free object URLs when leaving
  window.addEventListener('pagehide', () => revokeAll());
}

boot().catch((err) => {
  console.error('Wayfarer failed to start', err);
  const splash = $('boot-splash');
  if (splash) {
    splash.textContent = '';
    const note = document.createElement('div');
    note.className = 'paper';
    note.style.cssText = 'max-width:420px;margin:0 auto;padding:28px;text-align:center;';
    const h = document.createElement('h2');
    h.textContent = 'Wayfarer couldn’t open';
    const p = document.createElement('p');
    p.textContent = 'Something went wrong while starting the diary. Reloading usually fixes it.';
    const btn = document.createElement('button');
    btn.className = 'btn btn-primary';
    btn.textContent = 'Reload';
    btn.addEventListener('click', () => location.reload());
    note.append(h, p, btn);
    splash.appendChild(note);
  }
});
