// narratives.js — curated place-history library. OWNER: Builder 5.
// NARRATIVES + normalizeKey + lookupNarrative ported verbatim from
// legacy/wayfarer-v1.html. narrativeFor() is the ARCHITECTURE.md §3 contract
// wrapper: it returns { text: '', sourced: false } when a place is unknown
// (instead of the legacy "ask Claude" placeholder text).

/* =========================================================================
   CURATED HISTORICAL / CULTURAL NARRATIVE LIBRARY
   Keyed by normalized city/town name. General, well-established facts —
   meant as a solid starting draft, not the final word.
   ========================================================================= */
export const NARRATIVES = {
  "paris": "Paris grew from a Celtic settlement on the Île de la Cité over two thousand years ago into the seat of French kings and, after 1789, the stage for a revolution that reshaped Europe's politics. Baron Haussmann's 19th-century rebuilding gave it the wide boulevards and cream-stone facades travelers recognize today, while the Eiffel Tower — built as a temporary centerpiece for the 1889 World's Fair — became the symbol nobody wanted torn down. The city's museums hold some of the deepest collections of art anywhere, a legacy of both royal patronage and empire.",
  "london": "London began as Londinium, a Roman trading post founded around 43 AD on the Thames, and has been rebuilt over itself many times since — most dramatically after the Great Fire of 1666, which cleared the medieval city and gave Christopher Wren his chance to redesign it in stone and dome. Centuries as the capital of a global empire filled it with wealth, immigration, and institutions — Parliament, the Tower, the British Museum — that still define its skyline and its arguments about history.",
  "rome": "Rome's history stretches back to a legendary founding in 753 BC and the rise of a republic-turned-empire that ruled most of the known Western world. The Colosseum, Forum, and Pantheon are not ruins so much as a city built in layers — medieval churches sit on Roman foundations, and Renaissance palaces reused ancient stone. It has also been the seat of the Catholic Church for nearly two thousand years, giving it a second, parallel history running alongside the empire's.",
  "florence": "Florence's wealth from wool and banking funded the Renaissance almost single-handedly through the Medici family, who bankrolled Michelangelo, Botticelli, and Brunelleschi's dome — still the largest masonry dome ever built when it was finished in 1436. Walking its center, largely unchanged since the 15th and 16th centuries, is close to walking through the moment Europe reinvented how it painted, built, and thought about the individual.",
  "venice": "Venice was built on more than a hundred small islands in a lagoon, starting as a refuge from mainland invasions in the 5th century, and grew into a maritime republic that controlled Mediterranean trade for a thousand years. Its wealth came from spices, silk, and glass, and its architecture — a mix of Byzantine, Gothic, and Islamic influence — reflects a city that always looked east as much as west. It has no cars; canals and footbridges still do the work streets do elsewhere.",
  "barcelona": "Barcelona's roots go back to Roman Barcino, but its personality today owes the most to the late 19th and early 20th centuries, when Catalan modernisme — led by Antoni Gaudí — reshaped the city with organic, sculptural buildings like the still-unfinished Sagrada Família. It's also the historic capital of Catalonia, a region with its own language and a long, sometimes tense relationship with the Spanish state, which shows up in the city's flags and murals as much as its museums.",
  "istanbul": "Istanbul has been a capital under three names and three empires — Byzantium, then Constantinople under Rome and Byzantium, then Istanbul under the Ottomans after 1453 — sitting exactly on the strait dividing Europe from Asia. The Hagia Sophia, built in 537 AD as a cathedral, later became a mosque and a museum before returning to use as a mosque, a fair summary of a city that keeps rewriting itself while keeping the same skyline of domes and minarets.",
  "athens": "Athens gave the world democracy, theater, and philosophy in roughly the 5th century BC, a period concentrated enough that the Acropolis, the Agora, and the works of Socrates, Plato, and Aristotle all trace to a single few generations. The city declined for long stretches afterward under Roman, Byzantine, and Ottoman rule before becoming the capital of modern Greece in 1834, which is why ancient marble and 19th-century neoclassicism sit side by side.",
  "oia": "The villages of Santorini sit on the rim of a caldera formed by one of the largest volcanic eruptions in human history, around 1600 BC — an event some scholars connect to the Atlantis legend and to the collapse of Minoan civilization on nearby Crete. The white-washed, blue-domed architecture is relatively recent, built to reflect heat and withstand wind, and the island has been rebuilt more than once after earthquakes, most recently in 1956.",
  "fira": "Santorini's caldera towns sit atop the rim of a volcano that erupted catastrophically around 1600 BC, an event that may have inspired the Atlantis myth and reshaped the ancient Aegean world. Fira, the modern capital, rebuilt itself after a severe 1956 earthquake in the same whitewashed, cave-house style that has defined the island for generations.",
  "prague": "Prague survived the 20th century's wars largely intact, which is why its Gothic, Baroque, and Art Nouveau layers — from Charles Bridge (started 1357) to Prague Castle, in continuous use since the 9th century — are unusually complete for a Central European capital. It was the heart of the Holy Roman Empire under Charles IV in the 14th century, and later a center of the Habsburg empire, the Prague Spring of 1968, and the Velvet Revolution of 1989.",
  "amsterdam": "Amsterdam's ring of concentric canals, dug in the 17th century during the Dutch Golden Age, was a feat of urban planning built on trade wealth from the Dutch East India Company — the world's first publicly traded corporation. That same century filled the city with the merchant houses and art (Rembrandt, Vermeer) that still define it, while its long tradition of religious tolerance shaped a famously open, pragmatic civic culture.",
  "reykjavik": "Reykjavik is usually dated to 874 AD, when the Norse settler Ingólfur Arnarson is said to have made it Iceland's first permanent settlement. For most of its history it stayed a small fishing town — the population didn't cross a few thousand until the 20th century — before rapid growth after Iceland's 1944 independence from Denmark turned it into the country's political, cultural, and economic center, all still powered largely by the geothermal energy beneath it.",
  "marrakech": "Marrakech was founded in 1070 by the Almoravid dynasty as a base for their empire across North Africa and Spain, and its walled medina — a UNESCO World Heritage site — has functioned as a working market and residential quarter for nearly a thousand years since. The Koutoubia Mosque's minaret, finished in the 12th century, set the design template later echoed by Seville's Giralda and Rabat's Hassan Tower.",
  "cairo": "Cairo as a city dates to 969 AD, but it sits beside monuments far older — the Giza pyramids and Sphinx were already more than two thousand years old when Cairo was founded. As the seat of the Fatimid, Mamluk, and later Ottoman rule in Egypt, it accumulated one of the densest collections of medieval Islamic architecture anywhere, layered on top of a Nile-side geography that has anchored Egyptian civilization for five thousand years.",
  "wadi musa": "Petra, carved into rose-colored sandstone cliffs by the Nabataeans starting around the 4th century BC, was a wealthy caravan-trade hub controlling incense and spice routes across Arabia. Its famous facade, Al-Khazneh (\"the Treasury\"), is a tomb, not a treasury — the name comes from a legend about hidden riches. Largely abandoned after a 4th-century earthquake and shifting trade routes, it was unknown to the West until 1812 and named a UNESCO World Heritage Site in 1985.",
  "petra": "Petra was carved into rose-colored sandstone cliffs by the Nabataeans starting around the 4th century BC, growing wealthy as a hub for caravan trade in incense and spices across Arabia. Al-Khazneh, its famous rock-cut facade, is actually a royal tomb — the name \"Treasury\" comes from a later legend about hidden riches. An earthquake and shifting trade routes emptied the city by the 7th century; it stayed largely unknown outside the region until 1812.",
  "dubai": "Dubai was a modest pearling and trading port on the Gulf until oil revenue, discovered in the 1960s, funded a deliberate transformation into a global business and tourism hub over the following decades. Much of what defines it today — the Burj Khalifa, the man-made Palm islands, the free-trade zones — was built within a single generation, making it one of the fastest urban transformations anywhere in the world.",
  "jaipur": "Jaipur was founded in 1727 by Maharaja Sawai Jai Singh II, a keen astronomer, and is one of the earliest planned cities in India, laid out on a grid according to principles from an ancient Indian architectural text. Its buildings were painted pink in 1876 to welcome the Prince of Wales, a color the city has kept ever since, earning it the nickname \"the Pink City.\" The Jantar Mantar observatory nearby holds the world's largest stone sundial.",
  "varanasi": "Varanasi, on the banks of the Ganges, is considered one of the oldest continuously inhabited cities in the world, with a religious history in Hinduism stretching back at least 3,000 years. It's one of Hinduism's seven holiest cities, where pilgrims come to bathe in the river and where cremation ghats have operated for centuries in the belief that dying here brings liberation from the cycle of rebirth.",
  "bangkok": "Bangkok became Thailand's capital in 1782 when King Rama I moved the royal seat across the Chao Phraya River after the fall of the former capital, Ayutthaya, and modeled the new city's temples and layout partly on the older one. The Grand Palace and Wat Phra Kaew (Temple of the Emerald Buddha) date to that founding era, while the city's canals, once its main transport network, earned it the old nickname \"Venice of the East.\"",
  "chiang mai": "Chiang Mai was founded in 1296 as the capital of the independent Lanna kingdom, whose distinct architecture, dialect, and Buddhist traditions still separate the region culturally from Bangkok and central Thailand. Its old city is still ringed by a moat and remnants of the original brick walls, and it remains one of the most important centers of northern Thai Buddhism, with hundreds of temples inside a compact historic core.",
  "hanoi": "Hanoi has been a capital on and off for roughly a thousand years, first as Thang Long under the Ly dynasty in 1010. French colonial rule from the late 19th century added the boulevards, opera house, and villa architecture of the Old Quarter, while the 20th century made it the capital first of French Indochina's resistance and then of a unified Vietnam after 1975 — layers you can trace walking from temple to colonial building to Communist-era monument.",
  "hoi an": "Hoi An was one of Southeast Asia's most important trading ports from the 15th to 19th centuries, where Chinese, Japanese, Dutch, and other merchants settled and left their mark — the Japanese Covered Bridge, Chinese assembly halls, and centuries-old wooden shophouses all still stand in a historic center preserved almost intact and recognized by UNESCO in 1999. Silk-making and tailoring, trades the town has practiced for centuries, remain central to its economy today.",
  "siem reap": "Siem Reap is the gateway to Angkor, the capital of the Khmer Empire from roughly the 9th to 15th centuries and, at Angkor Wat, home to the largest religious monument in the world. Built in the early 12th century originally as a Hindu temple to Vishnu before becoming Buddhist, Angkor Wat is only the centerpiece of a much larger complex of temples, reservoirs, and roads that once supported a city of perhaps a million people.",
  "ubud": "Ubud sits in the highlands of Bali and has been the island's artistic and spiritual heart for centuries, home to royal palaces, hundreds of temples, and a tradition of painting, woodcarving, and dance patronized by Balinese royalty since the 19th century. Balinese Hinduism, distinct from Indian Hinduism and woven with older animist beliefs, shapes daily life here through the small offerings placed on doorsteps and shrines every morning.",
  "kyoto": "Kyoto was Japan's imperial capital for over a thousand years, from 794 to 1868, and largely escaped bombing in World War II, leaving it with the country's densest concentration of temples, shrines, and traditional wooden architecture — over 1,600 Buddhist temples and 400 Shinto shrines. It remains the center of traditional Japanese arts including geisha culture, tea ceremony, and kaiseki cuisine, all developed and refined here over centuries of imperial and shogunate patronage.",
  "tokyo": "Tokyo was a small fishing village called Edo until 1603, when it became the seat of the Tokugawa shogunate and grew into one of the world's largest cities within two centuries. Renamed Tokyo (\"Eastern Capital\") when the emperor moved there in 1868, it was largely rebuilt twice in the 20th century — after the 1923 earthquake and after WWII firebombing — which is part of why it's now one of the most modern-looking cities its age anywhere.",
  "seoul": "Seoul has been a capital city for over 600 years, since the Joseon dynasty established it in 1394, and its five grand palaces — including Gyeongbokgung — date to that founding era, though most were rebuilt after destruction during Japanese invasions and colonial rule. Divided from the North since the Korean War armistice in 1953, it rebuilt itself into one of the world's major economic and cultural capitals within a single generation.",
  "new york": "New York began as the Dutch trading post New Amsterdam in 1624, seized by the English in 1664 and renamed for the Duke of York. Waves of immigration through Ellis Island from the 1890s to 1920s built much of the city's character, while the 20th century's skyscraper boom — the Chrysler Building, the Empire State Building — turned its skyline into shorthand for modern ambition itself.",
  "new york city": "New York began as the Dutch trading post New Amsterdam in 1624, seized by the English in 1664 and renamed for the Duke of York. Waves of immigration through Ellis Island from the 1890s to 1920s built much of the city's character, while the 20th century's skyscraper boom — the Chrysler Building, the Empire State Building — turned its skyline into shorthand for modern ambition itself.",
  "san francisco": "San Francisco was a small settlement until the 1848 Gold Rush turned it into a boomtown almost overnight, with its population exploding from around 1,000 to 25,000 in a single year. Rebuilt after the devastating 1906 earthquake and fire, it later became a center of counterculture in the 1960s and of technology from the 1970s onward — the Golden Gate Bridge, finished in 1937, remains the city's clearest symbol of that early engineering ambition.",
  "mexico city": "Mexico City is built directly on top of Tenochtitlan, the Aztec capital founded around 1325 on an island in Lake Texcoco, which the Spanish razed and rebuilt after conquering it in 1521. The lake was gradually drained over centuries, which is why the city sinks unevenly today, and the Zócalo, its central square, sits on the ruins of the Aztec Templo Mayor, parts of which are still being excavated beneath colonial-era buildings.",
  "cusco": "Cusco was the capital of the Inca Empire, laid out — according to tradition — in the shape of a puma, with massive stone walls whose precision-cut blocks still fit together without mortar. It's the traditional gateway to Machu Picchu, the Inca citadel built around 1450 in the Andes and abandoned within a century, likely during the Spanish conquest, before being brought to wider international attention in 1911.",
  "aguas calientes": "This small town below Machu Picchu exists almost entirely to serve travelers to the Inca citadel above it, built around 1450 as a royal estate for the emperor Pachacuti and abandoned roughly a century later, likely around the time of the Spanish conquest. Its remote mountainside position may be exactly why the Spanish never found it — it was never \"lost\" to the local Quechua population, but it stayed largely unknown internationally until it was brought to wider attention in 1911.",
  "rio de janeiro": "Rio de Janeiro was Brazil's capital for nearly two centuries, until 1960, and its Christ the Redeemer statue, completed in 1931 atop Corcovado mountain, became a 20th-century symbol of the city's identity. Founded by the Portuguese in 1565, it later briefly became the seat of the entire Portuguese empire when the royal family fled Napoleon's invasion of Portugal in 1808 — one of very few times a European monarchy has ruled from the Americas.",
  "buenos aires": "Buenos Aires was founded twice by the Spanish — first in 1536, abandoned after conflict with indigenous groups, then refounded in 1580 — before growing into one of the wealthiest cities in the world by the early 20th century on the back of beef and grain exports, which is why its center is filled with grand European-style architecture. It's also the birthplace of tango, which emerged in the working-class port neighborhoods in the late 1800s.",
  "cape town": "Cape Town began in 1652 as a supply station for Dutch East India Company ships rounding the Cape on the route to Asia, making it one of the oldest colonial settlements in sub-Saharan Africa. Table Mountain, overlooking the city, is among the oldest mountains in the world, and nearby Robben Island, where Nelson Mandela was imprisoned for 18 years, anchors the city's more recent history of apartheid and its end in the 1990s.",
  "sydney": "Sydney began in 1788 as a British penal colony at Sydney Cove, the first European settlement in Australia, on land the Gadigal people had lived on for tens of thousands of years. The Sydney Opera House, finished in 1973 after a famously troubled 14-year construction, and the Harbour Bridge, opened in 1932, are relatively recent additions to a much longer history that starts with the world's oldest continuous human culture.",
  "queenstown": "Queenstown grew out of a gold rush in the 1860s in New Zealand's Otago region, and the surrounding Southern Alps and lake country have since made it the country's adventure-tourism capital — it's often credited as the birthplace of commercial bungy jumping in 1988. The area was also long used by Māori travelers as a route to greenstone (pounamu) sources, a material central to Māori culture and craft."
};

/** Own-property lookup guard: a place normalizing to 'constructor' /
    'toString' etc. must not resolve inherited Object.prototype members as
    narratives. */
function hasNarrative(key) {
  return Object.prototype.hasOwnProperty.call(NARRATIVES, key);
}

/** Normalize a place name into a NARRATIVES key. Ported verbatim from v1. */
export function normalizeKey(s) {
  return (s || "").toLowerCase().trim()
    .replace(/^(the|st\.?|saint)\s+/, "")
    .replace(/[^a-z0-9\s]/g, "")
    .trim();
}

/**
 * Legacy lookup, ported verbatim from v1: always returns text — a friendly
 * "write your own" placeholder when the place is unknown.
 * @returns {{ text: string, sourced: boolean }}
 */
export function lookupNarrative(city) {
  const key = normalizeKey(city);
  if (hasNarrative(key)) return { text: NARRATIVES[key], sourced: true };
  return {
    text: `Wayfarer doesn't have a pre-written history for ${city || "this place"} yet. Add your own notes below, or ask Claude (or any research assistant) to write a short history of ${city || "this location"} and paste it in — it'll be saved with the rest of your diary.`,
    sourced: false
  };
}

/**
 * Contract lookup (ARCHITECTURE.md §3): tries the full place name, then the
 * part before the first comma ('Kyoto, Japan' → 'kyoto'). Unknown places get
 * sourced=false with an empty text so callers can fall back to the user's
 * own story.
 * @param {string} placeName
 * @returns {{ text: string, sourced: boolean }}
 */
export function narrativeFor(placeName) {
  const full = normalizeKey(placeName);
  if (hasNarrative(full)) return { text: NARRATIVES[full], sourced: true };
  const city = normalizeKey(String(placeName || '').split(',')[0]);
  if (hasNarrative(city)) return { text: NARRATIVES[city], sourced: true };
  return { text: '', sourced: false };
}
